[project]
name = "jungle-janitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["eth-ape>=0.8.24", "silverback>=0.6.5"]

[tool.uv]
dev-dependencies = ["ruff>=0.9.1"]
